### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type 'report_engine.Models.CustomerPlanModel' to type 'System.Collections.IList'

### ISSUE THREAD

**Issue by rcalderoni** [damienbod/AspNetCoreCsvImportExport#4]
System.InvalidCastException: Unable to cast object of type 'report_engine.Models.CustomerPlanModel' to type 'System.Collections.IList'

On line 68 of CsvInputFormatter.cs

`list = (IList)Activator.CreateInstance(itemType);`

Not sure why, my class is simple it's just two string properties...

```
public class CustomerPlanModel
    {
        public string CustomerNumber { get; set; }
        public string PlanId { get; set; }
    }
```

Note I did change the CsvDelimeter to "," instead of ";" and I am POSTing over:

```
CustomerNumber,PlanId
CUS-091090129301823,1420fosj
CUS-019209123,fdsojwi3
CUS-91302920139,dsds908
```

Edit: tried using ";" as the original code does and it still gave me the same error...

**Comment by damienbod** [comment]
Hi @rcalderoni 
You need to use a IList type to import the data. In your Controller, your import method should look something like this:

```
[HttpPost]
[Route("import")]
public IActionResult Import([FromBody]List<CustomerPlanModel> value)
{
  if (!ModelState.IsValid)
  {
                return BadRequest(ModelState);
  }
  else
   {
                List<CustomerPlanModel> data = value;
                return Ok();
  }
}
```

**Comment by rcalderoni** [comment]
yep, that's what I've got as well

```
[HttpPost]
        [Route("import")]
        public IActionResult Import([FromBody]List<CustomerPlanModel> value)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            else
            {
                List<CustomerPlanModel> data = value;
                return Ok();
            }
        }
```

```
public void ConfigureServices(IServiceCollection services)
        {
            var csvFormatterOptions = new CsvFormatterOptions();

            // Add framework services.
            services.AddMvc(options =>
            {
                options.InputFormatters.Add(new CsvInputFormatter(csvFormatterOptions));
                options.OutputFormatters.Add(new CsvOutputFormatter(csvFormatterOptions));
                options.FormatterMappings.SetMediaTypeMappingForFormat("csv", MediaTypeHeaderValue.Parse("text/csv"));
            });

            services.AddTransient<IReportFilterService, ReportFilterService>();
            services.AddTransient<IReportFilterRepository, ReportFilterRepository>();
        }
```

**Comment by damienbod** [comment]
If your using the an older version, then it's a compatibility issue, you need to change the Activator. The code works with the actual version of ASP.NET Core.

Greetings Damien

**Comment by damienbod** [comment]
can I close this issue?

**Comment by rcalderoni** [comment]
I ultimately used a different approach because I couldn't get past this. I
was using the latest version of Core, I suspect that this is still an issue
but did not pursue it further.

**Comment by damienbod** [comment]
OK, I'll check it again with Version ASP.NET Core 1.1 and if it works, I'll close the issue.

Thanks for the replay

Greetings Damien

**Comment by damienbod** [comment]
I check this and it works without problems.

https://github.com/damienbod/AspNetCoreCsvImportExport/tree/delimiterTestComma

This was the update in ASP.NET Core version which caused this mismatch. Sorry this solution did not work for you.

Greetings Damien
