### ISSUE TITLE
Default file name for exported csv file

### ISSUE THREAD

**Issue by sylvaincaillot** [damienbod/AspNetCoreCsvImportExport#5]
Hello, 
I have been using you code for exporting data from an IQueryable into a CSV file and it works fine.
I just would like to know how can I parametrize the Save window? For example, by giving a default file name (for the time being it's taking the name of my controller without the file extension), Save as type?

Thank you

Sylvain

**Comment by damienbod** [comment]
Hi Sylvain

At present it is defined in the Route attribute. You could change this and use the class name from the type and redirect or you could pass it as a parameter in the route.

Greetings Damien

**Comment by sylvaincaillot** [comment]
Thank you Damien for your quick answer, I will start using the Route attribute then.

Greetings to you too.
S.
